"""empty message

Revision ID: 0b84869e1b54
Revises: e9db9751d2dc
Create Date: 2021-05-25 11:42:06.443335

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b84869e1b54'
down_revision = 'e9db9751d2dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('article_views', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'article_views')
    # ### end Alembic commands ###
