"""empty message

Revision ID: cf932cc7a4ee
Revises: 2d8d8d71d885
Create Date: 2021-06-13 13:22:54.616430

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf932cc7a4ee'
down_revision = '2d8d8d71d885'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('owner', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_contact_read_time', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('last_sub_read_time', sa.DateTime(), nullable=True))
        batch_op.drop_column('last_message_read_time')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('owner', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_message_read_time', sa.DATETIME(), nullable=True))
        batch_op.drop_column('last_sub_read_time')
        batch_op.drop_column('last_contact_read_time')

    # ### end Alembic commands ###
