"""empty message

Revision ID: efd696ef697c
Revises: 0b84869e1b54
Create Date: 2021-05-30 11:30:07.550689

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'efd696ef697c'
down_revision = '0b84869e1b54'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=128), nullable=False),
    sa.Column('description', sa.String(length=264), nullable=False),
    sa.Column('product_url', sa.String(length=500), nullable=False),
    sa.Column('product_image', sa.LargeBinary(), nullable=True),
    sa.Column('product_image_name', sa.String(length=64), nullable=True),
    sa.Column('product_views', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('product')
    # ### end Alembic commands ###
